<ResultScreen>
    id: resultscreen
    name: resultscreen
    ScrollView:
        orientation: 'vertical'
        mg_bg_color: 1,0,1,1
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        MDList:
            MDLabel:
                text: "Pesquisa"
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                size_hint_x: .0500
                size_hint_y: .06
                halign: "center"